// ar.ts
export const arabicMessages = {
  ra: {
    action: {
      add_filter: 'إضافة فلتر',
      add: 'إضافة',
      back: 'رجوع',
      bulk_actions: '%{smart_count} عنصر محدد',
      cancel: 'إلغاء',
      clear_input_value: 'مسح القيمة',
      clone: 'نسخ',
      confirm: 'تأكيد',
      create: 'إنشاء',
      create_item: 'إنشاء %{item}',
      delete: 'حذف',
      edit: 'تعديل',
      export: 'تصدير',
      list: 'قائمة',
      refresh: 'تحديث',
      remove_filter: 'إزالة هذا الفلتر',
      remove: 'إزالة',
      save: 'حفظ',
      search: 'بحث',
      show: 'عرض',
      sort: 'ترتيب',
      undo: 'تراجع',
      expand: 'توسيع',
      close: 'إغلاق',
      open_menu: 'فتح القائمة',
      close_menu: 'إغلاق القائمة',
      saved_queries: 'saved_queries',
    },
    boolean: {
      true: 'نعم',
      false: 'لا',
      null: ' ',
    },
    page: {
      create: 'إنشاء %{name}',
      dashboard: 'لوحة التحكم',
      edit: '%{name} #%{id}',
      error: 'حدث خطأ',
      list: '%{name}',
      loading: 'جارٍ التحميل',
      not_found: 'غير موجود',
      show: '%{name} #%{id}',
      empty: 'لا يوجد %{name} حتى الآن.',
      invite: 'هل تريد إضافة واحد؟',
    },
    input: {
      file: {
        upload_several: 'اسحب بعض الملفات لإسقاطها، أو انقر لاختيار ملف.',
        upload_single: 'اسحب ملفًا لإسقاطه، أو انقر لاختياره.',
      },
      image: {
        upload_several: 'اسحب بعض الصور لإسقاطها، أو انقر لاختيار صورة.',
        upload_single: 'اسحب صورة لإسقاطها، أو انقر لاختيارها.',
      },
      references: {
        all_missing: 'تعذر العثور على بيانات المراجع.',
        many_missing: 'واحدة أو أكثر من المراجع المرتبطة لم تعد متوفرة.',
        single_missing: 'المرجع المرتبط لم يعد متوفراً.',
      },
    },
    message: {
      about: 'حول',
      are_you_sure: 'هل أنت متأكد؟',
      bulk_delete_content:
        'هل أنت متأكد أنك تريد حذف %{name}؟ |||| هل أنت متأكد أنك تريد حذف %{smart_count} عناصر؟',
      bulk_delete_title: 'حذف %{name} |||| حذف %{smart_count} %{name}',
      delete_content: 'هل أنت متأكد أنك تريد حذف هذا العنصر؟',
      delete_title: 'حذف %{name} #%{id}',
      details: 'تفاصيل',
      error: 'حدث خطأ في العميل ولم يتم إكمال طلبك.',
      invalid_form: 'النموذج غير صالح. يرجى التحقق من الأخطاء.',
      loading: 'جارٍ التحميل، يرجى الانتظار...',
      no: 'لا',
      not_found: 'إما أنك كتبت رابطًا خاطئًا، أو اتبعت رابطًا غير صالح.',
      yes: 'نعم',
    },
    navigation: {
      no_results: 'لا توجد نتائج',
      no_more_results: 'رقم الصفحة %{page} خارج النطاق. جرب الصفحة السابقة.',
      page_out_of_boundaries: 'رقم الصفحة %{page} خارج النطاق',
      page_out_from_end: 'لا توجد صفحات بعد',
      page_out_from_begin: 'لا توجد صفحات قبل',
      page_range_info: '%{offsetBegin}-%{offsetEnd} من %{total}',
      partial_page_range_info: '%{offsetBegin}-%{offsetEnd} من أكثر من %{offsetEnd}',
      current_page: 'الصفحة %{page}',
      page: 'الصفحة',
      first: 'الأولى',
      last: 'الأخيرة',
      next: 'التالي',
      previous: 'السابق',
      page_rows_per_page: 'صفوف لكل صفحة:',
      skip_nav: 'تخطي إلى المحتوى',
    },
    sort: {
      sort_by: 'ترتيب حسب %{field} %{order}',
      ASC: 'تصاعدي',
      DESC: 'تنازلي',
    },
    auth: {
      auth_check_error: 'يرجى تسجيل الدخول للمتابعة',
      user_menu: 'الملف الشخصي',
      username: 'اسم المستخدم',
      password: 'كلمة المرور',
      sign_in: 'تسجيل الدخول',
      sign_in_error: 'فشل تسجيل الدخول، يرجى المحاولة مرة أخرى',
      logout: 'تسجيل الخروج',
    },
    notification: {
      updated: 'تم تحديث العنصر |||| تم تحديث %{smart_count} عناصر',
      created: 'تم الإنشاء',
      deleted: 'تم حذف العنصر |||| تم حذف %{smart_count} عناصر',
      bad_item: 'عنصر غير صحيح',
      item_doesnt_exist: 'العنصر غير موجود',
      http_error: 'خطأ في الاتصال بالخادم',
      data_provider_error: 'خطأ في مزود البيانات. تحقق من وحدة التحكم.',
      canceled: 'تم الإلغاء',
      logged_out: 'تم إنهاء جلستك، يرجى إعادة الاتصال.',
    },
    validation: {
      required: 'مطلوب',
      minLength: 'يجب أن يكون على الأقل %{min} حرفًا',
      maxLength: 'يجب أن يكون %{max} حرفًا أو أقل',
      minValue: 'يجب أن يكون على الأقل %{min}',
      maxValue: 'يجب أن يكون %{max} أو أقل',
      number: 'يجب أن يكون رقمًا',
      email: 'يجب أن يكون بريدًا إلكترونيًا صالحًا',
      oneOf: 'يجب أن يكون واحدًا من: %{options}',
      regex: 'يجب أن يطابق النمط المحدد (regexp): %{pattern}',
    },
    configurable: { customize: 'jjj' },
  },
  resources: {
    notes: {
      name: ' مذكرات |||| مذكرة',
      fields: {
        id: 'الرمز التعريفي',
        created_at: 'تاريخ الإنشاء',
        created_by: 'أنشأه',
        updated_at: 'تاريخ آخر تعديل',
        updated_by: 'عدله',
        teacher_id: 'المدرس',
        pages: 'عدد الصفحات',
        cover_url: 'رابط الغلاف',
        year: 'السنة',
        subject_id: 'المادة',
        academic_year: 'السنة الدراسية',
        default_paper_size: 'حجم الورق الافتراضي',
        term_id: 'الفصل الدراسي',
        additional_data: 'بيانات إضافية',
        related_notes: 'مذكرات ذات صلة',
        nickname: 'الاسم المستعار',
        do_round: 'تدوير السعر',
        price: 'السعر',
      },
      actions: {
        create: 'إنشاء م',
        reserve: 'بدء الحجز',
        cancel_reserve: 'بدء الحجز',
        confirm_reserve: 'بدء الحجز',
      },
      errors: {
        teacher_id_required: 'يجب اختيار المدرس',
      },
      backendErrors: {
        'null value in column "teacher_id" of relation "notes" violates not-null constraint':
          'يجب اختيار المدرس',
      },
    },
  },
  custom: {
    currency: { short: 'ج.م', long: 'جنيه مصري' },
    filters: {
      academic_year: 'السنة الدراسية',
      subject: 'المادة',
      year: 'السنة',
      term_id: 'الترم',
    },
  },
};
