import { TranslationMessages } from 'ra-core';
import { Enums } from 'types/supabase-generated.types';

export const arabicMessages: TranslationMessages = {
  ra: {
    action: {
      add_filter: 'إضافة فلتر',
      add: 'إضافة',
      back: 'رجوع',
      bulk_actions: '%{smart_count} عنصر محدد',
      cancel: 'إلغاء',
      clear_input_value: 'مسح القيمة',
      clear_array_input: 'مسح القائمة',
      clone: 'نسخ',
      confirm: 'تأكيد',
      create: 'إنشاء',
      create_item: 'إنشاء %{item}',
      delete: 'حذف',
      edit: 'تعديل',
      export: 'تصدير',
      list: 'قائمة',
      print: 'طباعة',
      refresh: 'تحديث',
      remove_filter: 'إزالة هذا الفلتر',
      remove_all_filters: 'إزالة جميع الفلاتر',
      remove: 'إزالة',
      save: 'حفظ',
      search: 'بحث',
      search_columns: 'بحث في الأعمدة',
      select_all: 'تحديد الكل',
      select_row: 'تحديد هذا الصف',
      select_all_button: 'تحديد الكل (زر)',
      show: 'عرض',
      sort: 'ترتيب',
      undo: 'تراجع',
      unselect: 'إلغاء التحديد',
      expand: 'توسيع',
      close: 'إغلاق',
      open_menu: 'فتح القائمة',
      close_menu: 'إغلاق القائمة',
      update: 'تحديث',
      move_up: 'تحريك للأعلى',
      move_down: 'تحريك للأسفل',
      open: 'فتح',
      toggle_theme: 'تبديل السمة',
      select_columns: 'اختيار الأعمدة',
      update_application: 'تحديث التطبيق',
      saved_queries: {
        label: 'الاستعلامات المحفوظة',
        help: 'احفظ عمليات البحث الخاصة بك لاستخدامها لاحقًا',
      },
    },
    boolean: {
      true: 'نعم',
      false: 'لا',
      null: ' ',
    },
    page: {
      create: 'إنشاء %{name}',
      dashboard: 'لوحة التحكم',
      edit: '%{name} #%{id}',
      error: 'حدث خطأ',
      list: '%{name}',
      loading: 'جارٍ التحميل',
      not_found: 'غير موجود',
      show: '%{name} #%{id}',
      empty: 'لا يوجد %{name} حتى الآن.',
      invite: 'هل تريد إضافة واحد؟',
      access_denied: 'تم رفض الوصول',
      authentication_error: 'خطأ في المصادقة',
    },
    input: {
      file: {
        upload_several: 'اسحب بعض الملفات لإسقاطها، أو انقر لاختيار ملف.',
        upload_single: 'اسحب ملفًا لإسقاطه، أو انقر لاختياره.',
      },
      image: {
        upload_several: 'اسحب بعض الصور لإسقاطها، أو انقر لاختيار صورة.',
        upload_single: 'اسحب صورة لإسقاطها، أو انقر لاختيارها.',
      },
      references: {
        all_missing: 'تعذر العثور على بيانات المراجع.',
        many_missing: 'واحدة أو أكثر من المراجع المرتبطة لم تعد متوفرة.',
        single_missing: 'المرجع المرتبط لم يعد متوفراً.',
      },
      password: {
        toggle_visible: 'إظهار كلمة المرور',
        toggle_hidden: 'إخفاء كلمة المرور',
      },
    },
    saved_queries: {
      label: 'الاستعلامات المحفوظة',
      query_name: 'اسم الاستعلام',
      new_label: 'حفظ الاستعلام الحالي...',
      new_dialog_title: 'حفظ الاستعلام الحالي كاستعلام محفوظ',
      remove_label: 'حذف الاستعلام المحفوظ',
      remove_label_with_name: 'حذف الاستعلام "%{name}"',
      remove_dialog_title: 'حذف الاستعلام المحفوظ؟',
      remove_message: 'هل أنت متأكد أنك تريد حذف هذا الاستعلام من قائمتك المحفوظة؟',
      help: 'فلتر الاستعلامات، احفظ الاستعلامات الحالية لاستخدامها لاحقًا',
    },
    message: {
      about: 'حول',
      are_you_sure: 'هل أنت متأكد؟',
      access_denied: 'تم رفض الوصول',
      authentication_error: 'خطأ في المصادقة',
      auth_error: 'خطأ في تسجيل الدخول',
      bulk_delete_content:
        'هل أنت متأكد أنك تريد حذف %{name}؟ |||| هل أنت متأكد أنك تريد حذف %{smart_count} عناصر؟',
      bulk_delete_title: 'حذف %{name} |||| حذف %{smart_count} %{name}',
      bulk_update_content:
        'هل أنت متأكد أنك تريد تحديث هذا العنصر؟ |||| هل أنت متأكد أنك تريد تحديث %{smart_count} عناصر؟',
      bulk_update_title: 'تحديث %{name} |||| تحديث %{smart_count} %{name}',
      delete_content: 'هل أنت متأكد أنك تريد حذف هذا العنصر؟',
      delete_title: 'حذف %{name} #%{id}',
      details: 'تفاصيل',
      error: 'حدث خطأ في العميل ولم يتم إكمال طلبك.',
      invalid_form: 'النموذج غير صالح. يرجى التحقق من الأخطاء.',
      loading: 'جارٍ التحميل، يرجى الانتظار...',
      no: 'لا',
      not_found: 'إما أنك كتبت رابطًا خاطئًا، أو اتبعت رابطًا غير صالح.',
      yes: 'نعم',
      unsaved_changes: 'لم يتم حفظ بعض التغييرات. هل أنت متأكد أنك تريد تجاهلها؟',
      placeholder_data_warning: 'تم استرجاع بعض البيانات غير مكتملة (placeholders).',
      clear_array_input: 'هل تريد بالتأكيد مسح جميع العناصر؟',
      select_all_limit_reached: 'لقد وصلت إلى الحد الأقصى من العناصر التي يمكن تحديدها.',
    },
    navigation: {
      no_results: 'لا توجد نتائج',
      no_filtered_results: 'لم يتم العثور على نتائج مطابقة للفلتر الحالي',
      clear_filters: 'إزالة جميع الفلاتر',
      no_more_results: 'رقم الصفحة %{page} خارج النطاق. جرب الصفحة السابقة.',
      page_out_of_boundaries: 'رقم الصفحة %{page} خارج النطاق',
      page_out_from_end: 'لا توجد صفحات بعد',
      page_out_from_begin: 'لا توجد صفحات قبل',
      page_range_info: '%{offsetBegin}-%{offsetEnd} من %{total}',
      partial_page_range_info: '%{offsetBegin}-%{offsetEnd} من أكثر من %{offsetEnd}',
      current_page: 'الصفحة %{page}',
      page: 'الصفحة',
      first: 'الأولى',
      last: 'الأخيرة',
      next: 'التالي',
      previous: 'السابق',
      page_rows_per_page: 'صفوف لكل صفحة:',
      skip_nav: 'تخطي إلى المحتوى',
    },
    sort: {
      sort_by: 'ترتيب حسب %{field} %{order}',
      ASC: 'تصاعدي',
      DESC: 'تنازلي',
    },
    auth: {
      auth_check_error: 'الرجاء تسجيل الدخول للمتابعة',
      user_menu: 'القائمة الشخصية',
      username: 'اسم المستخدم',
      password: 'كلمة المرور',
      email: 'البريد الإلكتروني',
      sign_in: 'تسجيل الدخول',
      sign_in_error: 'فشل تسجيل الدخول، حاول مرة أخرى',
      logout: 'تسجيل الخروج',
    },
    notification: {
      updated: 'تم التحديث بنجاح',
      created: 'تم الإنشاء بنجاح',
      deleted: 'تم الحذف بنجاح',
      bad_item: 'عنصر غير صالح',
      item_doesnt_exist: 'العنصر غير موجود',
      http_error: 'خطأ في الاتصال بالخادم',
      data_provider_error: 'خطأ في مزود البيانات',
      canceled: 'تم الإلغاء',
      logged_out: 'تم تسجيل الخروج',
      i18n_error: 'تعذر تحميل الترجمات',
      not_authorized: 'غير مسموح لك بتنفيذ هذا الإجراء',
      application_update_available: 'يوجد تحديث جديد للتطبيق، يرجى إعادة تحميل الصفحة',
      offline: 'أنت غير متصل بالإنترنت',
    },
    validation: {
      required: 'مطلوب',
      minLength: 'يجب أن يكون على الأقل %{min} حرفًا',
      maxLength: 'يجب أن يكون %{max} حرفًا أو أقل',
      minValue: 'يجب أن يكون على الأقل %{min}',
      maxValue: 'يجب أن يكون %{max} أو أقل',
      number: 'يجب أن يكون رقمًا',
      email: 'يجب أن يكون بريدًا إلكترونيًا صالحًا',
      oneOf: 'يجب أن يكون واحدًا من: %{options}',
      regex: 'يجب أن يطابق النمط المحدد (regexp): %{pattern}',
    },
    configurable: {
      customize: 'تخصيص',
      configureMode: 'وضع التهيئة',
      inspector: {
        title: 'المفتش',
        content: 'حدد العناصر التي تريد تكوينها',
        reset: 'إعادة الضبط',
        hideAll: 'إخفاء الكل',
        showAll: 'إظهار الكل',
      },
      Datagrid: {
        title: 'جدول البيانات',
        unlabeled: 'عمود غير معنّون',
      },
      SimpleForm: {
        title: 'نموذج بسيط',
        unlabeled: 'string',
      },
      SimpleList: {
        title: 'قائمة بسيطة',
        primaryText: 'النص الأساسي',
        secondaryText: 'النص الثانوي',
        tertiaryText: 'النص الثالث',
      },
    },
  },
  resources: {
    branches: {
      name: 'فرع |||| الفروع',
      fields: {
        id: 'المعرّف',
        name: 'اسم الفرع',
        admin: 'المسؤول',
        avatar_url: 'الصورة',
        location: 'الموقع',
        location_geo: 'الإحداثيات الجغرافية',
        phone_number: 'أرقام الهاتف',
        whats_app_number: 'رقم واتساب',
      },
      actions: {
        choose: 'اختر الفرع',
        set_default: 'تعيين كافتراضي',
        contact: 'تواصل مع الفرع',
        edit: 'تعديل الفرع',
        delete: 'حذف الفرع',
        create: 'إضافة فرع جديد',
      },
      labels: {
        details: 'تفاصيل الفرع',
        contact_info: 'معلومات الاتصال',
        geo: 'الموقع الجغرافي',
        list: 'قائمة الفروع',
        create: 'إضافة فرع',
        edit: 'تعديل الفرع',
        show: 'عرض الفرع',
      },
    },
    cover_types: {
      name: 'غلاف |||| الأغلفة',
      fields: {
        id: 'المعرّف',
        name: 'اسم الغلاف',
        to_paper_size: 'مناسب للورق مقاس',
      },
      actions: {
        choose: 'اختر المقاس',
        set_default: 'تعيين كافتراضي',
        edit: 'تعديل بيانات الغلاف',
        create: 'إضافة نوع غلاف جديد',
      },
      labels: {
        details: 'تفاصيل الغلاف',
      },
    },
    publications: {
      name: ' مصادر تعليمية |||| مصدر تعليمي',
      fields: {
        id: 'الرمز التعريفي',
        created_at: 'تاريخ الإنشاء',
        created_by: 'أنشأه',
        updated_at: 'تاريخ آخر تعديل',
        updated_by: 'عدله',
        publisher: 'الناشر',
        publication_type: 'نوع المصدر',
        pages: 'عدد الصفحات',
        cover_url: 'رابط الغلاف',
        year: 'السنة',
        subject_id: 'المادة',
        academic_year: 'السنة الدراسية',
        paper_type: 'نوع الورق',
        cover_type: 'نوع الغلاف',
        term: 'الفصل الدراسي',
        additional_data: 'بيانات إضافية',
        related_publications: 'مصادر ذات صلة',
        do_round: 'تدوير السعر',
        change_price: { oneFacePrice: 'للوجه الواحد', twoFacesPrice: 'للوجهين' },
        two_faces_cover: 'غلاف مطبوع على الوجهين',
        coverless: 'بدون غلاف',
        dublix: 'طباعة على الوجهين',
      },
      actions: {
        create: 'إنشاء مذكرة',
      },
      labels: {
        price: 'السعر',
        publications_types: {
          ['note' as Enums<'publications_types'>]: 'مذكرة',
          ['book' as Enums<'publications_types'>]: 'كتاب',
          ['other' as Enums<'publications_types'>]: 'أخرى',
        },
        term: {
          ['1st' as Enums<'term'>]: 'الأول',
          ['2nd' as Enums<'term'>]: 'الثاني',
          ['full_year' as Enums<'term'>]: 'مدمج (سنة كاملة)',
        },
      },
      messages: {
        related_publications_modal_title: 'منشورات ذات صلة',
        select_publications_to_add: 'اختر المنشورات للإضافة:',
        select_and_add_all: 'تحديد وإضافة الكل',
        price_label: 'السعر',
        group_price_title: 'سعر المجموعة المحددة',
        publications_count: 'عدد المنشورات',
        total_items_with_quantity: 'إجمالي العناصر (مع الكمية)',
        separate_prices_sum: 'مجموع الأسعار المنفصلة',
        group_price_label: 'سعر المجموعة',
        savings_label: 'التوفير',
        add_selected_single: 'إضافة المنشور المحدد',
        add_selected_multiple: 'إضافة المحددة',
        no_additional_data: 'لا توجد بيانات إضافية',
        no_related_publications: 'لا توجد منشورات مرتبطة',
        create_related_success: 'تم إنشاء المنشور المرتبط بنجاح',
        update_original_error: 'خطأ في تحديث المنشور الأصلي',
        create_related_error: 'خطأ في إنشاء المنشور الجديد',
        unexpected_error: 'حدث خطأ غير متوقع',
        image_load_error: 'خطأ في تحميل الصورة',
        parent_not_found: 'المنشور الأصلي غير موجود',
        change_price_help: 'تعديل السعر بقيمة (5, - 10 , إلخ ...) بالجنيه',
        cover_alt: 'الغلاف',
        remove_image: 'إزالة الصورة',
        save_and_manage_related: 'حفظ وإدارة المنشورات ذات الصلة',
        saving: 'جاري الحفظ...',
        save_related_publication: 'حفظ المنشور المرتبط',
        save_and_add_another: 'حفظ وإضافة آخر',
        created_related_count: 'تم إنشاء %{count} منشور مرتبط',
        or_paste_image: 'أو الصق صورة من الحافظة',
        create_related_title: 'إنشاء منشور مرتبط',
        not_found: 'المنشور غير موجود',
        view_publication: 'عرض المنشور',
        publication_data: 'بيانات المنشور',
        yes: 'نعم',
        no: 'لا',
        inherited_from_parent: 'الحقول الموروثة من المنشور الأصلي',
        // Collection master messages
        is_collection_master: 'المنشور الرئيسي للمجموعة',
        set_as_master: 'تعيين كرئيسي للمجموعة',
        set_master_success: 'تم تعيين المنشور كرئيسي للمجموعة بنجاح',
        set_master_error: 'فشل تعيين المنشور كرئيسي',
        master_deletion_title: 'حذف المنشور الرئيسي',
        master_deletion_warning: 'هذا المنشور هو الرئيسي للمجموعة. يرجى اختيار إجراء قبل الحذف.',
        select_new_master: 'اختيار رئيسي جديد للمجموعة',
        remove_from_group: 'حذف عناصر من المجموعة',
        select_items_to_remove: 'اختر العناصر التي تريد حذفها:',
        related_count: '%{count} منشورات مرتبطة',
        collection_items: 'عناصر المجموعة',
        group_total: 'إجمالي المجموعة',
        saved: 'وفرت',
      },
      filters: {
        show_separately: 'ضم المجموعة',
      },
    },
    users: {
      name: 'العملاء |||| عميل',
      fields: {
        id: 'الرمز التعريفي',
        created_at: 'تاريخ الإنشاء',
        avatar_url: 'رابط الصورة الرمزية',
        email: 'البريد الإلكتروني',
        full_name: 'الاسم الكامل',
        phone_number: 'رقم الهاتف',
        role: 'الدور',
        academic_years: 'السنة الدراسية',
      },
      actions: {
        create: 'عميل جديد',
        update: 'تحديث بيانات المستخدم',
        delete: 'حذف المستخدم',
        view: 'عرض تفاصيل المستخدم',
      },
      empty: 'لا يوجد عملاء',
    },
    reservations: {
      name: 'الحجوزات |||| حجز',
      fields: {
        id: 'الرمز التعريفي',
        client_id: 'العميل',
        created_at: 'تاريخ الحجز',
        created_by: 'حجزه',
        dead_line: 'موعد التسليم',
        paid_amount: 'المبلغ المدفوع',
        total_price: 'إجمالي السعر',
        remain_amount: 'المبلغ المتبقي',
        reservation_code: 'رقم الحجز',
        reservation_status: 'حالة الحجز',
        reserved_items: 'العناصر المحجوزة',
        delivered_at: 'تاريخ التسليم',
        delivered_by: 'تم التسليم بواسطة',
        note: 'ملاحظة',
        manual_price: 'سعر يدوي',
        unit_price: 'سعر الوحدة',
      },
      actions: {
        create: 'إنشاء حجز',
        deliver: 'تسليم الحجز',
        update: 'تعديل الحجز',
        cancel: 'إلغاء الحجز',
        confirm: 'تأكيد الحجز',
        confirm_direct: 'تأكيد الطباعة',
        direct: 'طباعة مباشرة',
        show: 'تفاصيل الحجز',
        pay: 'دفع المبلغ',
        add_custom: 'إضافة منشور مخصص',
      },
      labels: {
        details: 'تفاصيل الحجز',
        no_clients: 'لا يوجد عملاء',
        no_reserved_items: 'لا توجد منشورات محجوزة بعد',
      },
      messages: {
        no_items: 'لا توجد منشورات محجوزة بعد',
        reservation_created: 'تم إنشاء الحجز بنجاح',
        reservation_updated: 'تم تعديل الحجز بنجاح',
        direct_print_created: 'تم إنشاء الطباعة المباشرة بنجاح',
        direct_print_error: 'حدث خطأ أثناء إنشاء الطباعة المباشرة',
        direct_print_title: 'طباعة مباشرة #%{index}',
        pages_must_be_positive: 'يجب أن يكون عدد الصفحات أكبر من صفر',
        must_login: 'يجب تسجيل الدخول',
      },
      status: {
        'in-progress': 'قيد العمل',
        ready: 'جاهز للتسليم',
        delivered: 'تم تسليمه',
        canceled: 'تم إلغاؤه',
      },
    },
  },
  custom: {
    currency: { short: 'ج.م', long: 'جنيه مصري' },
    filters: {
      academic_year: 'السنة الدراسية',
      subject: 'المادة',
      publisher: 'الناشر',
      year: 'السنة',
      term_id: 'الترم',
    },
    production_summary: {
      title: 'ملخص الإنتاج',
      subtitle: 'ملخص الإنتاج - المطبوعات قيد التنفيذ',
      loading: 'جاري التحميل...',
      error: 'حدث خطأ أثناء جلب البيانات',
      no_publications: 'لا توجد مطبوعات قيد التنفيذ حالياً',
      total_unique: 'إجمالي المطبوعات الفريدة',
      total_quantity: 'إجمالي الكمية',
      paper: 'ورقة',
      filters: {
        deadline_from: 'موعد التسليم من',
        deadline_to: 'موعد التسليم إلى',
      },
      print: {
        button: 'طباعة الملخص',
        tracking: 'التتبع',
        printed_covers: 'الأغلفة المطبوعة',
      },
      table: {
        number: '#',
        publication_name: 'اسم المطبوعة',
        quantity_required: 'الكمية المطلوبة',
      },
      fields: {
        paper_type_id: 'نوع الورق',
        cover_type_id: 'نوع الغلاف',
        isDublix: 'دوبلكس',
        manualPrice: 'سعر يدوي',
        note: 'ملاحظة',
      },
    },

    // ─── Shared atomic labels (reused across pages, tables, forms) ───
    labels: {
      client: 'العميل',
      paper_size: 'مقاس الورق',
      total_price: 'المبلغ الإجمالي',
      paid_amount: 'المبلغ المدفوع',
      remain_amount: 'المبلغ المتبقي',
      no_remain_amount: 'خالص الثمن',
      current_year: 'العام الدراسي الحالي',
      current_term: 'الفصل الدراسي الحالي',
      price_ceil_to: 'تقريب الأسعار إلى',
      branch_phone_numbers: 'أرقام تليفونات الفرع',
      phone_number: 'رقم التليفون',
      deliver_after: 'التسليم بعد __ ساعة',
      price: 'السعر',
      quantity: 'الكمية',
      title: 'العنوان',
      revenue: 'الإيرادات',
      academic_year: 'السنة الدراسية',
      term: 'الفصل الدراسي',
      publication_type: 'نوع المطبوعة',
      num_orders: 'عدد الطلبات',
      client_name: 'اسم العميل',
      total_purchases: 'إجمالي المشتريات',
      no_data: 'لا توجد بيانات لعرضها',
      set_now: 'الآن',
      instant_delivery: 'تسليم فوري',
      instant_delivery_confirmation: 'تأكيد التسليم الفوري',
      reserved_items: 'العناصر المحجوزة',
      pages_count: 'عدد الصفحات',
      item: 'عنصر',
      item_price: 'سعر العنصر',
      add_item: 'إضافة عنصر',
      reset_price: 'استعادة السعر',
      paper_price_per_100: 'سعر الورق/١٠٠',
      no_name: 'لا يوجد اسم',
      unknown: 'غير معروف',
      am: 'ص',
      pm: 'م',
      date_from: 'من تاريخ',
      date_to: 'إلى تاريخ',
      order_total: 'طلب إجمالي',
      duplex_print: 'طباعة على الوجهين',
      one_face_price_piasters: 'سعر الوجه الواحد بالقروش',
      two_faces_price_piasters: 'سعر الوجهين بالقروش',
      one_face_price_pounds: 'سعر الوجه الواحد بالجنيه',
      two_faces_price_pounds: 'سعر الوجهين بالجنيه',
      suitable_for: 'مناسب لمقاسات',
      set_as_unavailable: 'تعيين ك غير متاح',
      set_as_available: 'تعيين ك متاح',
      set_as_default: 'تعيين كإفتراضي',
      academic_years: {
        KG0: { name: 'قبل الحضانة', short_name: 'تأسيس' },
        KG1: { name: 'كي جي ون', short_name: 'KG1' },
        KG2: { name: 'كي جي تو', short_name: 'KG2' },
        '1st_primary': { name: 'أولى إبتدائي', short_name: '1ب' },
        '2nd_primary': { name: 'تانيه إبتدائي', short_name: '2ب' },
        '3rd_primary': { name: 'تالته إبتدائي', short_name: '3ب' },
        '4th_primary': { name: 'رابعة إبتدائي', short_name: '4ب' },
        '5th_primary': { name: 'خامسه إبتدائي', short_name: '5ب' },
        '6th_primary': { name: 'سادسه إبتدائي', short_name: '6ب' },
        '1st_preparatory': { name: 'أولى إعدادي', short_name: '1ع' },
        '2nd_preparatory': { name: 'تانيه إعدادي', short_name: '2ع' },
        '3rd_preparatory': { name: 'تالته إعدادي', short_name: '3ع' },
        '1st_secondary': { name: 'أولى ثانوي', short_name: '1ث' },
        '2nd_secondary': { name: 'تانيه ثانوي', short_name: '2ث' },
        '3rd_secondary': { name: ' تالته ثانوي', short_name: '3ث' },
      },
      terms: {
        ['1st' as Enums<'term'>]: { short_name: 'الأول', name: 'ترم أول' },
        ['2nd' as Enums<'term'>]: { short_name: 'الثاني', name: 'ترم ثاني' },
        ['full_year' as Enums<'term'>]: { short_name: 'مدمج (سنة كاملة)', name: 'سنة كاملة' },
      },
      publication_types: {
        note: 'مذكرة',
        book: 'كتاب',
        other: 'أخرى',
      },
    },

    // ─── Stat card titles & subtitles (shared by Dashboard, Analytics, Financial) ───
    stats: {
      today_revenue: 'إيرادات اليوم',
      in_progress_orders: 'طلبات قيد التنفيذ',
      total_orders_30d: 'إجمالي الطلبات (٣٠ يوم)',
      active_clients: 'العملاء النشطين',
      total_revenue: 'إجمالي الإيرادات',
      remaining_amounts: 'المبالغ المتبقية',
      unpaid_dues: 'مستحقات غير مدفوعة',
      avg_order_value: 'متوسط قيمة الطلب',
      avg_value: 'القيمة المتوسطة',
      completed_orders: 'الطلبات المكتملة',
      total_clients: 'إجمالي العملاء',
      on_time_delivery: 'التسليم في الموعد',
      late_delivery: 'التسليم المتأخر',
      late_orders: 'طلبات متأخرة',
      avg_delivery_time: 'متوسط وقت التسليم',
      hour: 'ساعة',
      from_total: 'من إجمالي',
      from: 'من',
      order: 'طلب',
      vip: 'VIP',
      from_orders: 'من %{count} طلب',
    },

    // ─── Chart labels (shared by Dashboard charts, Financial page, chart components) ───
    charts: {
      paid_full: 'مدفوع بالكامل',
      paid_partial: 'مدفوع جزئياً',
      unpaid: 'غير مدفوع',
      daily_revenue: 'الإيرادات اليومية',
      daily_orders: 'عدد الطلبات اليومية',
      orders: 'الطلبات',
      payment_status_dist: 'توزيع حالات الدفع',
    },

    // ─── Tab labels & section titles (shared by Dashboard data tabs, Analytics page) ───
    tabs: {
      best_selling: 'الأكثر مبيعاً',
      academic_year_dist: 'توزيع السنوات الدراسية',
      term_dist: 'توزيع الفصول الدراسية',
      publication_types: 'أنواع المطبوعات',
      top_clients: 'أفضل العملاء',
      top_publications: 'أفضل %{count} مطبوعات مبيعاً',
      top_clients_title: 'أفضل %{count} عملاء',
      sales_by_year: 'توزيع المبيعات حسب السنة الدراسية',
      sales_by_term: 'توزيع المبيعات حسب الفصل الدراسي',
      sales_by_type: 'توزيع المبيعات حسب نوع المطبوعة',
    },

    // ─── App-wide messages & notifications ───
    messages: {
      instant_delivery_warning: 'تأكد من تسليم جميع العناصر المحجوزة وتحصيل المبلغ الكامل',
      receipt_preview: 'معاينة الإيصال',
      receipt_header: 'إيصال استلام',
      delivery_date: 'موعد التسليم',
      thank_you: 'شكراً لتعاملكم معنا',
      reservation_id: 'رقم الحجز',
      store_name: 'مكتبة الصفوة',
      branch: 'فرع',
      item_name: 'الصنف',
      total: 'الإجمالي',
      note: 'ملاحظة',
      download_image: 'تحميل صورة',
      download_pdf: 'تحميل PDF',
      receipt_copy_customer: 'نسخة العميل',
      receipt_copy_store: 'نسخة المحل',
      reservation_no_items: 'لا توجد منشورات محجوزة',
      error_prefix: 'خطأ',
      invalid_phone: 'لا يبدو كرقم هاتف صحيح',
      no_reservations_to_update: 'لا توجد حجوزات للتحديث',
      no_matching_items: 'لا توجد عناصر مطابقة للتحديث',
      update_error: 'حدث خطأ أثناء التحديث',
      update_success: 'تم تحديث %{count} حجز بنجاح',
      confirm_ready_title: 'تأكيد تعيين المنشور كجاهز',
      confirm_ready_start: 'هل أنت متأكد من تعيين المنشور',
      confirm_ready_end: 'كجاهز في',
      confirm_ready_in_reservation: 'حجز؟',
      click_to_set_ready: 'انقر لتعيين هذا المنشور كجاهز في جميع الحجوزات',
    },

    not_found: {
      title: 'غير موجود',
      message: '٤٠٤: الصفحة غير موجودة',
    },

    // ─── Page-specific keys ───
    dashboard: {
      title: 'مرحباً بالصفوة',
      heading: 'لوحة التحكم',
      tabs: {
        quick_stats: 'الإحصائيات السريعة',
        charts: 'الرسوم البيانية',
        delivery_indicators: 'مؤشرات التسليم',
        data_analytics: 'تحليلات البيانات',
      },
    },
    analytics: {
      title: 'التحليلات والإحصائيات',
      load_error: 'فشل تحميل بيانات التحليلات',
    },
    financial: {
      title: 'التقارير المالية',
    },
    settings: {
      title: 'إعدادات %{branch}',
      general: 'إعدادات عامة',
      printing_prices: 'أسعار الطباعة',
      covers_prices: 'أسعار التغليف',
      reservation_local: 'إعدادات الحجز (محلية)',
      download_receipt: 'تحميل الإيصال عند الحجز',
      jpg_image: 'صورة JPG',
      no_download: 'بدون تحميل',
      auto_print: 'طباعة تلقائية',
      auto_print_desc: 'طباعة الإيصال تلقائياً عند الحجز',
      add_new_size: 'إضافة مقاس جديد',
      cannot_delete_used: 'لا يمكن حذف المقاس إذا كان يستخدم في أي من الموارد',
      missing_setting_id: 'معرّف الإعداد غير موجود',
    },
  },
};
