import { TranslationMessages } from 'ra-core';
import { Enums } from 'types/supabase-generated.types';

export const arabicMessages: TranslationMessages = {
  ra: {
    action: {
      add_filter: 'إضافة فلتر',
      add: 'إضافة',
      back: 'رجوع',
      bulk_actions: '%{smart_count} عنصر محدد',
      cancel: 'إلغاء',
      clear_input_value: 'مسح القيمة',
      clear_array_input: 'مسح القائمة',
      clone: 'نسخ',
      confirm: 'تأكيد',
      create: 'إنشاء',
      create_item: 'إنشاء %{item}',
      delete: 'حذف',
      edit: 'تعديل',
      export: 'تصدير',
      list: 'قائمة',
      refresh: 'تحديث',
      remove_filter: 'إزالة هذا الفلتر',
      remove_all_filters: 'إزالة جميع الفلاتر',
      remove: 'إزالة',
      save: 'حفظ',
      search: 'بحث',
      search_columns: 'بحث في الأعمدة',
      select_all: 'تحديد الكل',
      select_row: 'تحديد هذا الصف',
      select_all_button: 'تحديد الكل (زر)',
      show: 'عرض',
      sort: 'ترتيب',
      undo: 'تراجع',
      unselect: 'إلغاء التحديد',
      expand: 'توسيع',
      close: 'إغلاق',
      open_menu: 'فتح القائمة',
      close_menu: 'إغلاق القائمة',
      update: 'تحديث',
      move_up: 'تحريك للأعلى',
      move_down: 'تحريك للأسفل',
      open: 'فتح',
      toggle_theme: 'تبديل السمة',
      select_columns: 'اختيار الأعمدة',
      update_application: 'تحديث التطبيق',
      saved_queries: {
        label: 'الاستعلامات المحفوظة',
        help: 'احفظ عمليات البحث الخاصة بك لاستخدامها لاحقًا',
      },
    },
    boolean: {
      true: 'نعم',
      false: 'لا',
      null: ' ',
    },
    page: {
      create: 'إنشاء %{name}',
      dashboard: 'لوحة التحكم',
      edit: '%{name} #%{id}',
      error: 'حدث خطأ',
      list: '%{name}',
      loading: 'جارٍ التحميل',
      not_found: 'غير موجود',
      show: '%{name} #%{id}',
      empty: 'لا يوجد %{name} حتى الآن.',
      invite: 'هل تريد إضافة واحد؟',
      access_denied: 'تم رفض الوصول',
      authentication_error: 'خطأ في المصادقة',
    },
    input: {
      file: {
        upload_several: 'اسحب بعض الملفات لإسقاطها، أو انقر لاختيار ملف.',
        upload_single: 'اسحب ملفًا لإسقاطه، أو انقر لاختياره.',
      },
      image: {
        upload_several: 'اسحب بعض الصور لإسقاطها، أو انقر لاختيار صورة.',
        upload_single: 'اسحب صورة لإسقاطها، أو انقر لاختيارها.',
      },
      references: {
        all_missing: 'تعذر العثور على بيانات المراجع.',
        many_missing: 'واحدة أو أكثر من المراجع المرتبطة لم تعد متوفرة.',
        single_missing: 'المرجع المرتبط لم يعد متوفراً.',
      },
      password: {
        toggle_visible: 'إظهار كلمة المرور',
        toggle_hidden: 'إخفاء كلمة المرور',
      },
    },
    saved_queries: {
      label: 'الاستعلامات المحفوظة',
      query_name: 'اسم الاستعلام',
      new_label: 'حفظ الاستعلام الحالي...',
      new_dialog_title: 'حفظ الاستعلام الحالي كاستعلام محفوظ',
      remove_label: 'حذف الاستعلام المحفوظ',
      remove_label_with_name: 'حذف الاستعلام "%{name}"',
      remove_dialog_title: 'حذف الاستعلام المحفوظ؟',
      remove_message: 'هل أنت متأكد أنك تريد حذف هذا الاستعلام من قائمتك المحفوظة؟',
      help: 'فلتر الاستعلامات، احفظ الاستعلامات الحالية لاستخدامها لاحقًا',
    },
    message: {
      about: 'حول',
      are_you_sure: 'هل أنت متأكد؟',
      access_denied: 'تم رفض الوصول',
      authentication_error: 'خطأ في المصادقة',
      auth_error: 'خطأ في تسجيل الدخول',
      bulk_delete_content:
        'هل أنت متأكد أنك تريد حذف %{name}؟ |||| هل أنت متأكد أنك تريد حذف %{smart_count} عناصر؟',
      bulk_delete_title: 'حذف %{name} |||| حذف %{smart_count} %{name}',
      bulk_update_content:
        'هل أنت متأكد أنك تريد تحديث هذا العنصر؟ |||| هل أنت متأكد أنك تريد تحديث %{smart_count} عناصر؟',
      bulk_update_title: 'تحديث %{name} |||| تحديث %{smart_count} %{name}',
      delete_content: 'هل أنت متأكد أنك تريد حذف هذا العنصر؟',
      delete_title: 'حذف %{name} #%{id}',
      details: 'تفاصيل',
      error: 'حدث خطأ في العميل ولم يتم إكمال طلبك.',
      invalid_form: 'النموذج غير صالح. يرجى التحقق من الأخطاء.',
      loading: 'جارٍ التحميل، يرجى الانتظار...',
      no: 'لا',
      not_found: 'إما أنك كتبت رابطًا خاطئًا، أو اتبعت رابطًا غير صالح.',
      yes: 'نعم',
      unsaved_changes: 'لم يتم حفظ بعض التغييرات. هل أنت متأكد أنك تريد تجاهلها؟',
      placeholder_data_warning: 'تم استرجاع بعض البيانات غير مكتملة (placeholders).',
      clear_array_input: 'هل تريد بالتأكيد مسح جميع العناصر؟',
      select_all_limit_reached: 'لقد وصلت إلى الحد الأقصى من العناصر التي يمكن تحديدها.',
    },
    navigation: {
      no_results: 'لا توجد نتائج',
      no_filtered_results: 'لم يتم العثور على نتائج مطابقة للفلتر الحالي',
      clear_filters: 'إزالة جميع الفلاتر',
      no_more_results: 'رقم الصفحة %{page} خارج النطاق. جرب الصفحة السابقة.',
      page_out_of_boundaries: 'رقم الصفحة %{page} خارج النطاق',
      page_out_from_end: 'لا توجد صفحات بعد',
      page_out_from_begin: 'لا توجد صفحات قبل',
      page_range_info: '%{offsetBegin}-%{offsetEnd} من %{total}',
      partial_page_range_info: '%{offsetBegin}-%{offsetEnd} من أكثر من %{offsetEnd}',
      current_page: 'الصفحة %{page}',
      page: 'الصفحة',
      first: 'الأولى',
      last: 'الأخيرة',
      next: 'التالي',
      previous: 'السابق',
      page_rows_per_page: 'صفوف لكل صفحة:',
      skip_nav: 'تخطي إلى المحتوى',
    },
    sort: {
      sort_by: 'ترتيب حسب %{field} %{order}',
      ASC: 'تصاعدي',
      DESC: 'تنازلي',
    },
    auth: {
      auth_check_error: 'الرجاء تسجيل الدخول للمتابعة',
      user_menu: 'القائمة الشخصية',
      username: 'اسم المستخدم',
      password: 'كلمة المرور',
      email: 'البريد الإلكتروني',
      sign_in: 'تسجيل الدخول',
      sign_in_error: 'فشل تسجيل الدخول، حاول مرة أخرى',
      logout: 'تسجيل الخروج',
    },
    notification: {
      updated: 'تم التحديث بنجاح',
      created: 'تم الإنشاء بنجاح',
      deleted: 'تم الحذف بنجاح',
      bad_item: 'عنصر غير صالح',
      item_doesnt_exist: 'العنصر غير موجود',
      http_error: 'خطأ في الاتصال بالخادم',
      data_provider_error: 'خطأ في مزود البيانات',
      canceled: 'تم الإلغاء',
      logged_out: 'تم تسجيل الخروج',
      i18n_error: 'تعذر تحميل الترجمات',
      not_authorized: 'غير مسموح لك بتنفيذ هذا الإجراء',
      application_update_available: 'يوجد تحديث جديد للتطبيق، يرجى إعادة تحميل الصفحة',
      offline: 'أنت غير متصل بالإنترنت',
    },
    validation: {
      required: 'مطلوب',
      minLength: 'يجب أن يكون على الأقل %{min} حرفًا',
      maxLength: 'يجب أن يكون %{max} حرفًا أو أقل',
      minValue: 'يجب أن يكون على الأقل %{min}',
      maxValue: 'يجب أن يكون %{max} أو أقل',
      number: 'يجب أن يكون رقمًا',
      email: 'يجب أن يكون بريدًا إلكترونيًا صالحًا',
      oneOf: 'يجب أن يكون واحدًا من: %{options}',
      regex: 'يجب أن يطابق النمط المحدد (regexp): %{pattern}',
    },
    configurable: {
      customize: 'تخصيص',
      configureMode: 'وضع التهيئة',
      inspector: {
        title: 'المفتش',
        content: 'حدد العناصر التي تريد تكوينها',
        reset: 'إعادة الضبط',
        hideAll: 'إخفاء الكل',
        showAll: 'إظهار الكل',
      },
      Datagrid: {
        title: 'جدول البيانات',
        unlabeled: 'عمود غير معنّون',
      },
      SimpleForm: {
        title: 'نموذج بسيط',
        unlabeled: 'string',
      },
      SimpleList: {
        title: 'قائمة بسيطة',
        primaryText: 'النص الأساسي',
        secondaryText: 'النص الثانوي',
        tertiaryText: 'النص الثالث',
      },
    },
  },
  resources: {
    branches: {
      name: 'فرع |||| الفروع',
      fields: {
        id: 'المعرّف',
        name: 'اسم الفرع',
        admin: 'المسؤول',
        avatar_url: 'الصورة',
        location: 'الموقع',
        location_geo: 'الإحداثيات الجغرافية',
        phone_number: 'أرقام الهاتف',
        whats_app_number: 'رقم واتساب',
      },
      actions: {
        choose: 'اختر الفرع',
        set_default: 'تعيين كافتراضي',
        contact: 'تواصل مع الفرع',
        edit: 'تعديل الفرع',
        delete: 'حذف الفرع',
        create: 'إضافة فرع جديد',
      },
      labels: {
        details: 'تفاصيل الفرع',
        contact_info: 'معلومات الاتصال',
        geo: 'الموقع الجغرافي',
        list: 'قائمة الفروع',
        create: 'إضافة فرع',
        edit: 'تعديل الفرع',
        show: 'عرض الفرع',
      },
    },
    cover_types: {
      name: 'غلاف |||| الأغلفة',
      fields: {
        id: 'المعرّف',
        name: 'اسم الغلاف',
        to_paper_size: 'مناسب للورق مقاس',
      },
      actions: {
        choose: 'اختر المقاس',
        set_default: 'تعيين كافتراضي',
        edit: 'تعديل بيانات الغلاف',
        create: 'إضافة نوع غلاف جديد',
      },
      labels: {
        details: 'تفاصيل الغلاف',
      },
    },
    publications: {
      name: ' مصادر تعليمية |||| مصدر تعليمي',
      fields: {
        id: 'الرمز التعريفي',
        created_at: 'تاريخ الإنشاء',
        created_by: 'أنشأه',
        updated_at: 'تاريخ آخر تعديل',
        updated_by: 'عدله',
        publisher: 'الناشر',
        publication_type: 'نوع المصدر',
        pages: 'عدد الصفحات',
        cover_url: 'رابط الغلاف',
        year: 'السنة',
        subject_id: 'المادة',
        academic_year: 'السنة الدراسية',
        default_paper_size: 'حجم الورق الافتراضي',
        term: 'الفصل الدراسي',
        additional_data: 'بيانات إضافية',
        related_publications: 'مصادر ذات صلة',
        do_round: 'تدوير السعر',
        change_price: { oneFacePrice: 'للوجه الواحد', twoFacesPrice: 'للوجهين' },
        two_faces_cover: 'غلاف مطبوع على الوجهين',
      },
      actions: {
        create: 'إنشاء مذكرة',
      },
      labels: {
        price: 'السعر',
        publications_types: {
          ['note' as Enums<'publications_types'>]: 'مذكرة',
          ['book' as Enums<'publications_types'>]: 'كتاب',
          ['other' as Enums<'publications_types'>]: 'أخرى',
        },
        term: {
          ['1st' as Enums<'term'>]: 'الأول',
          ['2nd' as Enums<'term'>]: 'الثاني',
          ['full_year' as Enums<'term'>]: 'مدمج (سنة كاملة)',
        },
      },
    },
    users: {
      name: 'المستخدمون |||| مستخدم',
      fields: {
        id: 'الرمز التعريفي',
        created_at: 'تاريخ الإنشاء',
        avatar_url: 'رابط الصورة الرمزية',
        email: 'البريد الإلكتروني',
        full_name: 'الاسم الكامل',
        phone_number: 'رقم الهاتف',
        role: 'الدور',
      },
      actions: {
        create: 'إنشاء مستخدم',
        update: 'تحديث بيانات المستخدم',
        delete: 'حذف المستخدم',
        view: 'عرض تفاصيل المستخدم',
      },
    },
    reservations: {
      name: 'الحجوزات |||| حجز',
      fields: {
        id: 'الرمز التعريفي',
        client_id: 'العميل',
        created_at: 'تاريخ الإنشاء',
        created_by: 'أنشأه',
        dead_line: 'موعد التسليم',
        paid_amount: 'المبلغ المدفوع',
        remain_amount: 'المبلغ المتبقي',
        reservation_status: 'حالة الحجز',
        reserved_items: 'العناصر المحجوزة',
        total_price: 'السعر الإجمالي',
      },
      actions: {
        create: 'إنشاء حجز',
        deliver: 'تسليم الحجز',
        update: 'تعديل الحجز',
        cancel: 'إلغاء الحجز',
        confirm: 'تأكيد الحجز',
        pay: 'دفع المبلغ',
      },
      status: {
        'in-progress': 'قيد العمل',
        ready: 'جاهز للتسليم',
        delivered: 'تم تسليمه',
        canceled: 'تم إلغاؤه',
      },
    },
  },
  custom: {
    currency: { short: 'ج.م', long: 'جنيه مصري' },
    filters: {
      academic_year: 'السنة الدراسية',
      subject: 'المادة',
      year: 'السنة',
      term_id: 'الترم',
    },
    labels: {
      client: 'العميل',
      paper_size: 'حجم الورق',
      total_price: 'المبلغ الإجمالي',
      paid_amount: 'المبلغ المدفوع',
      remain_amount: 'المبلغ المتبقي',
      no_remain_amount: 'خالص الثمن',
      current_year: 'العام الدراسي الحالي',
      current_term: 'الفصل الدراسي الحالي',
      price_ceil_to: 'تقريب الأسعار إلى',
      academic_years: {
        KG0: { name: 'تأسيس', short_name: 'قبل الحضانة' },
        KG1: { name: 'كي جي ون', short_name: 'KG1' },
        KG2: { name: 'كي جي تو', short_name: 'KG2' },
        '1st_primary': { name: 'أولى إبتدائي', short_name: '1ب' },
        '2nd_primary': { name: 'تانيه إبتدائي', short_name: '2ب' },
        '3rd_primary': { name: 'تالته إبتدائي', short_name: '3ب' },
        '4th_primary': { name: 'رابعة إبتدائي', short_name: '4ب' },
        '5th_primary': { name: 'خامسه إبتدائي', short_name: '5ب' },
        '6th_primary': { name: 'سادسه إبتدائي', short_name: '6ب' },
        '1st_preparatory': { name: 'أولى إعدادي', short_name: '1ع' },
        '2nd_preparatory': { name: 'تانيه إعدادي', short_name: '2ع' },
        '3rd_preparatory': { name: 'تالته إعدادي', short_name: '3ع' },
        '1st_secondary': { name: 'أولى ثانوي', short_name: '1ث' },
        '2nd_secondary': { name: 'تانيه ثانوي', short_name: '2ث' },
        '3rd_secondary': { name: ' تالته ثانوي', short_name: '3ث' },
      },
    },
  },
};
